name: Build and Deploy the Gateway of Microservices

on:
  push:
    branches:
      - main
    paths:
      - "backend/gateway/**"
      - ".github/workflows/backend_gateway_deploy.yaml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker to use the Google Cloud Registry
        run: gcloud auth configure-docker

      - name: Build the Docker image
        working-directory: backend/gateway
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/gateway:latest .

      - name: Push the Docker image to GCP Container Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/gateway:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy gateway \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/gateway:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --port 8080
